#!/usr/bin/env python
import sys
import subprocess

# Ignore E203: Because of a[inds, :] for numpy arrays  + ['--ignore=E203']
subprocess.call(['pep8'] + sys.argv[1:])
subprocess.call(['pyflakes'] + sys.argv[1:])

sys.exit(0)
